language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pycodestyle
script:
  - PYTHONPATH=. pycodestyle tests/valgrind_parser_test.py valgrind_parser/valgrind_parser/valgrind_log_parser.py valgrind_parser/valgrind_parser/utils/html_converter.py valgrind_parser/valgrind_parser/utils/json_helper.py
  - PYTHONPATH=. pytest tests
